### ISSUE TITLE
Reject fixing

### ISSUE THREAD

**Issue by rotemchn** [orishac/WorkshopSoftwareEngineering#10]
- Print Eventlogs after each action
- Change exceptions to be more specific
- Arrange systemManager's logic
- Encrypt passwords
- Add main() function at Market
- Add threads - parallel programing
- Use Python's object-oriented quality - return objects rather than ID's
- Guest from member transfer - check functionality

**Comment by orishac** [comment]
fixed Exceptions types

**Comment by rotemchn** [comment]
When adding product quantity to a store we need to add that the quantity is greater than 0.

**Comment by rotemchn** [comment]
In the getCart function in the Market, print the cart nicely :)

**Comment by rotemchn** [comment]
Change updateProductFromCart function in the market to remove product-quantity from the cart, and also change the function accordingly in Bag and in Cart.

**Comment by rotemchn** [comment]
In purchaseCart function in the Market we neet to return the purchase id rather than True or False

**Comment by rotemchn** [comment]
In userTransaction we need to add printing by the print function in storeTransaction

**Comment by orishac** [comment]
Encrypt passwords - done

**Comment by barroz1996** [comment]
changed guest login to be automat, and initial hardcoded system manager

**Comment by orishac** [comment]
We need to implement use case 4.9 - Store closing
overall we need to fix now:
- 4.9 close store
- threads
- Use Python's object-oriented quality - return objects rather than ID's
- more logging fixing
- move guest cart to member at login_member

**Comment by barroz1996** [comment]
* have to add print to all DTO!

**Comment by orishac** [comment]
getRolesInformation should be able to be accessed for everyone in the system and not only store's stuff

**Comment by orishac** [comment]
Need to add: 
- getStore(storeId) method
- getUserStores(userId) method (return all the stores that the user have permission in)
- getAllStores() method

I wrote the methods in priority order (The first is the most important)

**Comment by kfirs127** [comment]
in the service, need to change all assigneeId to assigneeName.

**Comment by orishac** [comment]
searches should not be case-sensitive

**Comment by barroz1996** [comment]
> in the service, need to change all assigneeId to assigneeName.

Done

**Comment by kfirs127** [comment]
> 
added print after each event.
added threads.
aranged system manager logic
change to oop insted of Ids in the bussiens.
fixed the transfer from guest to member

**Comment by kfirs127** [comment]
> When adding product quantity to a store we need to add that the quantity is greater than 0.

done

**Comment by kfirs127** [comment]
> In purchaseCart function in the Market we neet to return the purchase id rather than True or False

Done

**Comment by kfirs127** [comment]
> We need to implement use case 4.9 - Store closing overall we need to fix now:
> 
> * 4.9 close store
> * threads
> * Use Python's object-oriented quality - return objects rather than ID's
> * more logging fixing
> * move guest cart to member at login_member

Done

**Comment by kfirs127** [comment]
> Need to add:
> 
> * getStore(storeId) method
> * getUserStores(userId) method (return all the stores that the user have permission in)
> * getAllStores() method
> 
> I wrote the methods in priority order (The first is the most important)

done.
added those 3 functions in roleService(just for semantic, not relly need to have a role to call those functions).

**Comment by barroz1996** [comment]
> searches should not be case-sensitive

Done

**Comment by orishac** [comment]
need to change admin logic

**Comment by orishac** [comment]
> need to change admin logic

done

**Comment by kfirs127** [comment]
issues from meeting of version 2:

1.  need to make sure that in all the time there is at lests one system manager(and that the Market cannot be open without it), 
     also need to add a test about it.
2. add notifications.
3. rewrite the Interface characterization, mostly the measures.
4. fix all the discount problems: discount/rule tress, tests and not with Ids - use the composite disign pattern
5. need to add purchase policys.
6. system manager can view how many users there is in the market.
7. add the test case when there is 3 users, u1, u2 and u3.
    u1 assign u2, u2 assign u3, u1 remove u2 and it should remove u3 automatically

**Comment by kfirs127** [comment]
> issues from meeting of version 2:

> 7. add the test case when there is 3 users, u1, u2 and u3.
>    u1 assign u2, u2 assign u3, u1 remove u2 and it should remove u3 automatically

issue num 7 is DONE

**Comment by kfirs127** [comment]
> issues from meeting of version 2:
> 
> 1. need to make sure that in all the time there is at lests one system manager(and that the Market cannot be open without it),
>    also need to add a test about it.
> 2. add notifications.
> 3. rewrite the Interface characterization, mostly the measures.
> 4. fix all the discount problems: discount/rule tress, tests and not with Ids - use the composite disign pattern
> 5. need to add purchase policys.
> 6. system manager can view how many users there is in the market.
> 7. add the test case when there is 3 users, u1, u2 and u3.
>    u1 assign u2, u2 assign u3, u1 remove u2 and it should remove u3 automatically

issues 4 & 5 is DONE

**Comment by rotemchn** [comment]
in member registration (memberSignUp function - in the service) the is no argument gust ID
כלומר אין קשר בין האורח לבין ה-member

**Comment by rotemchn** [comment]
add option to exit the system = unregister for members (not only for guests)

**Comment by rotemchn** [comment]
guest can log in twice ! (if he is logged in, he shouldn't succeed to log in again)

**Comment by kfirs127** [comment]
> issues from meeting of version 2:
> 
> 1. need to make sure that in all the time there is at lests one system manager(and that the Market cannot be open without it),
>    also need to add a test about it.
> 2. add notifications.
> 3. rewrite the Interface characterization, mostly the measures.
> 4. fix all the discount problems: discount/rule tress, tests and not with Ids - use the composite disign pattern
> 5. need to add purchase policys.
> 6. system manager can view how many users there is in the market.
> 7. add the test case when there is 3 users, u1, u2 and u3.
>    u1 assign u2, u2 assign u3, u1 remove u2 and it should remove u3 automatically

6 is DONE

**Comment by rotemchn** [comment]
> guest can log in twice ! (if he is logged in, he shouldn't succeed to log in again)

closed ! :)

**Comment by rotemchn** [comment]
login twice at the same time doesn't work :(

**Comment by rotemchn** [comment]
removeMember doesn't remove him from data base

**Comment by orishac** [comment]
> issues from meeting of version 2:
> 
> 1. need to make sure that in all the time there is at lests one system manager(and that the Market cannot be open without it),
>    also need to add a test about it.
> 2. add notifications.
> 3. rewrite the Interface characterization, mostly the measures.
> 4. fix all the discount problems: discount/rule tress, tests and not with Ids - use the composite disign pattern
> 5. need to add purchase policys.
> 6. system manager can view how many users there is in the market.
> 7. add the test case when there is 3 users, u1, u2 and u3.
>    u1 assign u2, u2 assign u3, u1 remove u2 and it should remove u3 automatically

2 - Added live notification, moving on to saved notifications

**Comment by orishac** [comment]
> issues from meeting of version 2:
> 
> 1. need to make sure that in all the time there is at lests one system manager(and that the Market cannot be open without it),
>    also need to add a test about it.
> 2. add notifications.
> 3. rewrite the Interface characterization, mostly the measures.
> 4. fix all the discount problems: discount/rule tress, tests and not with Ids - use the composite disign pattern
> 5. need to add purchase policys.
> 6. system manager can view how many users there is in the market.
> 7. add the test case when there is 3 users, u1, u2 and u3.
>    u1 assign u2, u2 assign u3, u1 remove u2 and it should remove u3 automatically

2 - DONE

**Comment by rotemchn** [comment]
system manager can't logout (but is supposed to be able to do that)

**Comment by rotemchn** [comment]
if two users try to register with the same username at the same time - they both succeed ! :(

**Comment by rotemchn** [comment]
> if two users try to register with the same username at the same time - they both succeed ! :(

Done :)

**Comment by rotemchn** [comment]
> system manager can't logout (but is supposed to be able to do that)

Done2 :)

**Comment by rotemchn** [comment]
> issues from meeting of version 2:
> 
> 1. need to make sure that in all the time there is at lests one system manager(and that the Market cannot be open without it),
>    also need to add a test about it.
> 2. add notifications.
> 3. rewrite the Interface characterization, mostly the measures.   Done 
> 4. fix all the discount problems: discount/rule tress, tests and not with Ids - use the composite disign pattern
> 5. need to add purchase policys.
> 6. system manager can view how many users there is in the market.
> 7. add the test case when there is 3 users, u1, u2 and u3.
>    u1 assign u2, u2 assign u3, u1 remove u2 and it should remove u3 automatically

1 is closed!

**Comment by orishac** [comment]
> > issues from meeting of version 2:
> > 
> > 1. need to make sure that in all the time there is at lests one system manager(and that the Market cannot be open without it),
> >    also need to add a test about it.
> > 2. add notifications.
> > 3. rewrite the Interface characterization, mostly the measures.
> > 4. fix all the discount problems: discount/rule tress, tests and not with Ids - use the composite disign pattern
> > 5. need to add purchase policys.
> > 6. system manager can view how many users there is in the market.
> > 7. add the test case when there is 3 users, u1, u2 and u3.
> >    u1 assign u2, u2 assign u3, u1 remove u2 and it should remove u3 automatically
> 
> issues 4 & 5 is DONE

3 & 7 Done
